[package]
name = "procmon"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive", "env", "string"] }
plotters = "0.3.7"
serde = { version = "1.0.217", features = ["serde_derive", "derive"] }
sysinfo = "0.33.1"
