[package]
name = "procmon"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env", "string"] }
plotters = "0.3.5"
serde = { version = "1.0.193", features = ["serde_derive", "derive"] }
sysinfo = "0.29.10"
